### ISSUE TITLE
0Auth

### ISSUE THREAD

**Issue by FlamesX-128** [MR-Addict/github-users#1]
I have a question, why don't you use Github Apps or 0Auth Apps instead asking user's email and password?
i think is more better

**Comment by MR-Addict** [comment]
Yeah, it’s a good idea. I may consider implement one of them later.

Thanks for your advice.

**Comment by MR-Addict** [comment]
@FlamesX-128, I had successfully implemented github oauth for signing in and managing users.

You can have a try if you want.

**Comment by FlamesX-128** [comment]
:+1:
